### ISSUE TITLE
Importing custom opportunity columns

### ISSUE THREAD

**Issue by dselman** [fivetran/dbt_salesforce#13]
I've a question about how to import custom Salesforce columns. We use FiveTran to run dbt against RedShift.

When I run the SQL command below I can see the custom columns are present in the `_tmp` table, but they are not being copied over to the `stg_salesforce__opportunity` table.

```
SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'stg_salesforce__opportunity_tmp' order by column_name asc
```

In `dbt_project.yml` I currently have this, where `contract_term_c` is one of the custom columns that I see on the `_tmp` table. 

```
  salesforce:
    opportunity_pass_through_columns: [contract_term_c]
  salesforce_source:
    opportunity_pass_through_columns: [contract_term_c]
```

Could you please explain how to get custom columns into the `stg_salesforce__opportunity` table, as well as into the `_enhanced` table?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dselman thanks for opening this issue! 

What you have provided looks like it should work. However, I have seen variable configuration within the `dbt_project.yml` get a bit mixed up if anything went wrong in specifying the variables at various levels. Would you be able to try and set the `opportunity_pass_through_columns` variable globally within your vars: section? See below for an example:

```yml
# dbt_project.yml

...
vars:
  salesforce_database: your-database-name
  salesforce_schema: your-schema-name
  opportunity_pass_through_columns: [contract_term_c]
```

If the above doesn't work would you be able to share your variables configuration within the `dbt_project.yml` file so we may do a deeper dive into the issue? 

Thanks!
