### ISSUE TITLE
[Bug] salesforce__contact_enhanced user passthrough columns

### ISSUE THREAD

**Issue by calder-holt** [fivetran/dbt_salesforce#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When adding passthrough columns to the salesforce__contact_enhanced model we receive a Database Error due to an incorrect alias. After looking into the compile sql it appears that the aliased columns are `user`, but the actual model references a cte called `salesforce_user`. 

### Relevant error log or model output

```shell
Finished running 11 view models, 18 table models, 34 tests, 2 hooks in 905.43s.

Completed with 1 error and 0 warnings:

Database Error in model salesforce__contact_enhanced (models/salesforce__contact_enhanced.sql)
syntax error at or near "."
LINE 77:     , created_date, user.quota_current_month_c, user.quota_c...
                                     ^
compiled SQL at target/run/salesforce/models/salesforce__contact_enhanced.sql

Done. PASS=60 WARN=0 ERROR=1 SKIP=2 TOTAL=63
```

### Expected behavior

The model will allow passthrough columns and compile correctly. 

### dbt Project configurations

```
  salesforce_source:
    +schema: salesforce_source
    enabled: true
    bind: false
    +tags:
    - "fivetran_salesforce"
  salesforce:
    +schema: mart_revops
    enabled: true
    bind: false
    +tags:
    - "fivetran_salesforce"

  salesforce_schema: salesforce
  salesforce_database: raw_fivetran
account_pass_through_columns: [created_date, created_by_id, implementation_tier_c, new_business_opportunity_c, active_recruiting_subscription_tier_c, churn_reason_c, renewal_at_risk_c, contract_end_date_c, ghsa_arr_company_wide_c, ghsa_arr_seats_quantity_c, ghsa_arr_seats_c, implementation_manager_c, account_executive_c, service_tier_c, gho_arr_c, ghr_arr_c, crm_arr_c, inclusion_arr_c, region_c, number_of_hires_30_c, number_of_hires_60_c, number_of_hires_90_c, number_of_hires_12_months_c, all_active_subscriptions_c, implementation_consultant_email_c]
  opportunity_pass_through_columns: [contract_length_c, created_by_id, last_stage_change_date, sdr_c, marketing_lead_source_c, arr_for_quota_c, date_reached_negotiate_c, date_reached_close_c, date_reached_validate_c, date_reached_develop_c, date_reached_prove_c, arr_up_for_renewal_gho_c, arr_up_for_renewal_ghr_c, arr_up_for_renewal_services_c, arr_up_for_renewal_total_c, arr_up_for_renewal_ghsa_company_wide_c, arr_up_for_renewal_ghsa_seats_c, gho_arr_c, ghr_arr_c, services_arr_c, ghsa_arr_company_wide_c, ghsa_arr_seats_c, ghsa_seats_quantity_c]
  user_pass_through_columns: [created_date, quota_current_month_c, quota_current_quarter_c, quota_current_year_c, time_to_first_opp_c, time_to_full_quota_c]
  contact_pass_through_columns: [created_date, created_by_id, marketing_lead_source_c, onboarding_demo_request_c, sourcing_automation_demo_request_c, converted_lead_id_c, lead_created_date_c, requested_demo_timestamp_c]
  lead_pass_through_columns: [sdr_c, world_region_c, marketing_lead_source_c, marketing_status_c, onboarding_demo_request_c, sourcing_automation_demo_request_c, converted_timestamp_c, mql_timestamp_c, requested_demo_timestamp_c]
Footer

```

### Package versions

version: [">=0.7.0", "<=0.8.0"]

### What database are you using dbt with?

redshift

### dbt Version

1.0.4

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
