### ISSUE TITLE
[Bug] Passthrough columns duplicating causing error on testing

### ISSUE THREAD

**Issue by rcaddell** [fivetran/dbt_salesforce#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Wen upgrading to version 9.1, we receive an error during the internal testing.  This appears to be due to the salesforce_source and the salesforce packages both taking the pass through columns from the staging models defined in the project variables

### Relevant error log or model output

```shell
The error is as follows:

>16:18:37  Database Error in test unique_salesforce__contact_enhanced_contact_id >(models/salesforce.yml)
>16:18:37    002090 (42601): SQL compilation error: error line 69 at position 53
>16:18:37    Unsupported: SELECT list element with multiple columns.
>16:18:37    compiled Code at target/run/salesforce/models/salesforce.yml/unique_salesforce__contact_enhanced_contact_id.sql

Complied Enhanced model:
`with contact as (

    select *
    from {{ var('contact') }}
), 

account as (

    select *
    from {{ var('account') }}
),

salesforce_user as (

    select *
    from {{ var('user') }}
)

select 
    contact.contact_id,
    contact.contact_name,
    contact.account_id,
    contact.department,
    contact.contact_description,
    contact.email,
    contact.individual_id,
    contact.is_deleted as contact_is_deleted,
    contact.last_activity_date,
    contact.lead_source,
    contact.mailing_city,
    contact.mailing_country,
    contact.mailing_country_code,
    contact.mailing_postal_code,
    contact.mailing_state,
    contact.mailing_state_code,
    contact.mailing_street,
    contact.master_record_id,
    contact.mobile_phone,
    contact.owner_id as contact_owner_id,
    contact.phone,
    contact.reports_to_id,
    salesforce_user.user_name as contact_owner_name,
    account.account_name,
    account.account_number,
    account.account_source,
    account.annual_revenue as account_annual_revenue,
    account.account_description,
    account.industry as account_industry,
    account.is_deleted as account_is_deleted,
    account.number_of_employees as account_number_of_employees,
    account.owner_id as account_owner_id,
    account.parent_id as account_parent_id,
    account.rating as account_rating,
    account.type as account_type

        --The below scripts allows for pass through columns.
    {{ fivetran_utils.persist_pass_through_columns(pass_through_variable='salesforce__contact_pass_through_columns', identifier='contact') }}
    {{ fivetran_utils.persist_pass_through_columns(pass_through_variable='salesforce__account_pass_through_columns', identifier='account') }}
    {{ fivetran_utils.persist_pass_through_columns(pass_through_variable='salesforce__user_pass_through_columns', identifier='salesforce_user') }}
    
from contact
left join account 
    on contact.account_id = account.account_id
left join salesforce_user
    on contact.owner_id = salesforce_user.user_id`


Compiled Contact staging model

`
with base as (

    select * 
    from {{ ref('stg_salesforce__contact_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_salesforce__contact_tmp')),
                staging_columns=get_contact_columns()
            )
        }}
        
    from base
), 

final as (
    
    select 
        cast(_fivetran_synced as {{ dbt.type_timestamp() }}) as _fivetran_synced,
        id as contact_id,
        account_id,
        department,
        description as contact_description,
        email,
        first_name,
        home_phone,
        individual_id,
        is_deleted,
        cast(last_activity_date as {{ dbt.type_timestamp() }}) as last_activity_date,
        last_modified_by_id,
        last_modified_date,
        last_name,
        last_referenced_date,
        cast(last_viewed_date as {{ dbt.type_timestamp() }}) as last_viewed_date,
        lead_source,
        mailing_city,
        mailing_country,
        mailing_country_code,
        mailing_postal_code,
        mailing_state,
        mailing_state_code,
        mailing_street,
        master_record_id,
        mobile_phone,
        name as contact_name,
        owner_id,
        phone,
        reports_to_id,
        title
        
        {{ fivetran_utils.fill_pass_through_columns('salesforce__contact_pass_through_columns') }}
        
    from fields
)

select *
from final
where not coalesce(is_deleted, false)`
```

### Expected behavior

The passthrough columns should only be passed once

### dbt Project configurations

```yml
vars:
    # variables related to the fivetran_log package
    fivetran_log:
        fivetran_log_database: raw
        fivetran_log_schema: fivetran_log
        fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic
        fivetran_log_using_triggers: false # this will disable only trigger_table logic
        fivetran_log_using_account_membership: false # this will disable only the account membership logic
        fivetran_log_using_destination_membership: false # this will disable only the destination membership logic
        fivetran_log_using_user: false # this will disable only the user logic
    # variables related to the fivetran_salesforce object.
    salesforce_database: raw
    salesforce_schema: salesforce
    salesforce__order_enabled: false # Disable if you do not have the user_role table
    using_account_history_mode_active_records: false
    using_opportunity_history_mode_active_records: true
    using_user_role_history_mode_active_records: false
    using_user_history_mode_active_records: false
    using_contact_history_mode_active_records: false
    using_lead_history_mode_active_records: false
    using_task_history_mode_active_records: false
    using_event_history_mode_active_records: false
    using_product_2_history_mode_active_records: false
    using_opportunity_line_item_history_mode_active_records: true
    salesforce__user_pass_through_columns: 
        - name: "telestream_id_c"
    salesforce__account_pass_through_columns:
        - name: "territory_c, account_region_c"
    salesforce__opportunity_pass_through_columns: 
        - name: "opportunity_number_c"
        - name: "region_c"
        - name: "opportunity_manager_c"
        - name: "last_modified_date"
        - name: "risk_upside_c"
        - name: "forecasted_amount_c"
        - name: "forecast_amount_override_c"
        - name: "commit_to_forecast_c"
        - name: "renewal_opportunity_c"
        - name: "partner_account_c"
        - name: "role_c"
        - name: "lost_c"
        - name: "lost_detail_c"
    salesforce__opportunity_line_item_pass_through_columns:
        - name: "product_group_static_c"
        - name: "product_bu_static_c"
        - name: "product_type_text_c"
        - name: "tek_product_name_c"
        - name: "description_c"
        - name: "sbqq_quote_line_c"
        - name: "support_begin_date_c"
        - name: "support_end_date_c"
        - name: "asset_c"
        - name: "serial_number_c"
    salesforce__product_2_pass_through_columns:
        - name: "sbqq_taxable_c"
        - name: "sbqq_component_c"
        - name: "sbqq_cost_editable_c"
        - name: "sbqq_custom_configuration_required_c"
        - name: "sbqq_description_locked_c"
        - name: "sbqq_exclude_from_maintenance_c"
        - name: "sbqq_exclude_from_opportunity_c"
        - name: "sbqq_hidden_c"
        - name: "sbqq_include_in_maintenance_c"
        - name: "sbqq_new_quote_group_c"
        - name: "sbqq_non_discountable_c"
        - name: "sbqq_non_partner_discountable_c"
        - name: "sbqq_optional_c"
        - name: "sbqq_price_editable_c"
        - name: "sbqq_pricing_method_editable_c"
        - name: "sbqq_reconfiguration_disabled_c"
        - name: "sbqq_hide_price_in_search_results_c"
        - name: "sbqq_quantity_editable_c"
        - name: "template_c"
        - name: "sbqq_has_configuration_attributes_c"
        - name: "force_price_book_inclusion_c"
        - name: "force_desktop_price_book_inclusion_c"
        - name: "sbqq_externally_configurable_c"
        - name: "sbqq_allocate_pot_on_orders_c"
        - name: "auto_calc_support_c"
        - name: "subscripton_term_pricing_c"
        - name: "sbqq_enable_large_configuration_c"
        - name: "use_product_name_as_contract_name_c"
        - name: "platform_contract_c"
        - name: "exclude_from_mapping_c"
        - name: "master_c"
        - name: "product_group_c"
        - name: "royalty_vendor_c"
        - name: "type_c"
        - name: "sbqq_pricing_method_c"
        - name: "sbqq_option_selection_method_c"
        - name: "sbqq_asset_conversion_c"
        - name: "sbqq_subscription_base_c"
        - name: "sbqq_subscription_type_c"
        - name: "sbqq_default_quantity_c"
        - name: "sbqq_block_pricing_field_c"
        - name: "sbqq_asset_amendment_behavior_c"
        - name: "groups_c"
        - name: "nav_product_id_c"
        - name: "product_sub_family_c"
        - name: "revision_no_c"
        - name: "pricebook_description_c"
        - name: "product_category_c"
        - name: "prod_pipe_report_primary_category_c"
        - name: "maintenance_allocation_perc_c"
        - name: "product_allocation_perc_c"
        - name: "stock_code_c"
        - name: "release_status_c"
        - name: "supp_tax_category_c"
        - name: "includes_appliance_c"
        - name: "prod_pipe_report_secondary_category_c"
        - name: "r_d_location_c"
        - name: "cogs_c"
        - name: "sbqq_subscription_category_c"
        - name: "variant_code_c"
        - name: "sbqq_sort_order_c"
        - name: "release_status_date_c"
        - name: "item_type_c"
        - name: "end_of_sale_c"
        - name: "price_book_sort_c"
        - name: "end_of_life_c"
        - name: "price_jira_link_c"
        - name: "support_level_c"
        - name: "renewal_support_c"
```

### Package versions

packages:

    - package: fivetran/fivetran_log 
      version: [">=0.7.0", "<0.8.0"]
    # extends testing in dbt.  
    - package: calogica/dbt_expectations 
      version: [">=0.8.0","<0.9.0"]
    # used to analyze Snowflake usage.
    - package: gitlabhq/snowflake_spend 
      version: 1.3.0
    # fivetran created packages to assist in analyzing Salesforce data. 
    - package: fivetran/salesforce_formula_utils
      version: [">=0.8.0", "<0.9.0"]
    - package: fivetran/salesforce 
      version: [">=0.9.0", "<0.10.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.5.2

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
