### ISSUE TITLE
Indicate which config-version should be used

### ISSUE THREAD

**Issue by angel-hernandez91** [fivetran/dbt_salesforce#7]
The docs which describe the `dbt_project.yml` set up should indicate that the `configure-version` should be set to `1` based on the provided vars example. Suggested fix:

```
# dbt_project.yml

config-version: 1
...

models:
    salesforce:
        vars:
            account: "{{ source('salesforce', 'account') }}"   # or "{{ ref('salesforce_account_unioned'}) }}"
            opportunity: "{{ source('salesforce', 'opportunity') }}" 
            user: "{{ source('salesforce', 'user') }}"
            user_role: "{{ source('salesforce', 'user_role') }}"

```
